---
title: "Observatorio Coyuntura CEDE (testing)"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    social: menu
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
```

### Mercado Inmobiliario

```{r}
library(leaflet)
library(sf)
library(tidyverse)

upla<-read_sf("upla/UPla.shp")
dta_2021<-readRDS("median.Rds")
pal <- colorNumeric(
  palette = "Reds",
  domain = dta_2021$median)


upla<-left_join(upla,dta_2021)
#Add labels
leaflet(upla) %>% 
  addTiles() %>% 
  addPolygons(label = paste(upla$UPlNombre,"Median Price=",upla$median, "Number of Properties=",upla$n),
              stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~pal(median))

```

***

Esta es la distribución geográfica de precios

[metodologia](https://ignaciomsarmiento.github.io/research.html)

### Mercado Laboral

```{r}
library(dygraphs)
dygraph(nhtemp, main = "Pedidos de Empleos") %>% 
  dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01"))
```

***
En testing



### Dinámica de Precios

```{r}
library(dygraphs)
dygraph(nhtemp, main = "Precios") %>% 
  dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01"))
```

***